"""test

Revision ID: 44def4ab7563
Revises: 
Create Date: 2021-09-11 00:24:12.340133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44def4ab7563'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('PublisherID', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('Summary', sa.String(length=255), nullable=True),
    sa.Column('Content', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['PublisherID'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Article')
    # ### end Alembic commands ###
